type Topic = {
  category: string;
  title: string;
  posts?: string;
};

export type TabContent = {
  [key: string]: Topic[];
};

export const tabContent: TabContent = {
  Brain: [
    { category: "Psychology", title: "Building habits" },
    { category: "Physiology", title: "Vagus nerve" },
    { category: "Biochemistry", title: "Dopamine rush" },
    { category: "Cognitive Science", title: "Memory gap" },
    { category: "Neurology", title: "Synapse fire" },
    { category: "Psychiatry", title: "Anxiety peak" },
    { category: "Genetics", title: "Mood switch" },
    { category: "Behavioral Science", title: "Focus trick" },
    { category: "Neurophysics", title: "Brain pulse" },
    { category: "Neuroscience", title: "Seretonin" },
  ],

  Body: [
    { category: "Respiratory Science", title: "Breathing from diaphragm" },
    { category: "Nutrition", title: "Gluten" },
    { category: "Endocrinology", title: "Insulin drop" },
    { category: "Anatomy", title: "Lung stretch" },
    { category: "Biophysics", title: "Blood pressure" },
    { category: "Microbiology", title: "Gut flora" },
    { category: "Exercise Science", title: "Muscle tear" },
    { category: "Immunology", title: "Antibody clash" },
    { category: "Pathology", title: "Wound seal" },
    { category: "Physiology", title: "Inflammation" },
    { category: "Medicine", title: "Virus block" },
    { category: "Nutrition", title: "Fat burn" },
    { category: "Endocrinology", title: "Hormone spike" },
    { category: "Physiology", title: "Oxygen flow" },
    { category: "Microbiology", title: "Pathogen fight" },
    { category: "Exercise Science", title: "Bone strength" },
    { category: "Genetics", title: "Risk marker" },
    { category: "Pathology", title: "Tumor shrink" },
    { category: "Immunology", title: "Fever peak" },
    { category: "Pharmacology", title: "Drug bind" },
  ],
  Nature: [
    { category: "Biology", title: "Cell split" },
    { category: "Botany", title: "Root depth" },
    { category: "Ecology", title: "Water cycle" },
    { category: "Zoology", title: "Wolf pack" },
    { category: "Genetics", title: "Trait jump" },
    { category: "Mycology", title: "Spore spread" },
    { category: "Evolution", title: "Fossil shift" },
    { category: "Marine Biology", title: "Tide pool" },
    { category: "Entomology", title: "Bee hive" },
    { category: "Ethology", title: "Bird migration" },
  ],
  Mind: [
    { category: "Philosophy", title: "Free choice" },
    { category: "Psychology", title: "Fear response" },
    { category: "Cognitive Science", title: "Logic trap" },
    { category: "Sociology", title: "Crowd sway" },
    { category: "Linguistics", title: "Sound meaning" },
    { category: "Ethics", title: "Truth cost" },
    { category: "Education", title: "Skill curve" },
    { category: "Logic", title: "Proof break" },
    { category: "Neuroscience", title: "Dream wave" },
    { category: "Behavioral Science", title: "Reward loop" },
  ],
  Cosmos: [
    { category: "Quantum Mechanics", title: "Photons" },
    { category: "Cosmology", title: "Big bang" },
    { category: "Astronomy", title: "Black holes" },
    { category: "Planetary Science", title: "Mars crust" },
    { category: "Stellar Physics", title: "Star collapse" },
    { category: "Particle Physics", title: "Neutron spin" },
    { category: "Relativity", title: "Space curve" },
    { category: "Astrochemistry", title: "Comet ice" },
    { category: "Galactic Dynamics", title: "Milky way" },
    { category: "Astrophysics", title: "Dark matter" },
    { category: "Astronomy", title: "Moon dust" },
    { category: "Cosmology", title: "Void stretch" },
    { category: "Astrophysics", title: "Pulsar beat" },
    { category: "Planetary Science", title: "Ring spin" },
    { category: "Space Exploration", title: "Orbit path" },
    { category: "Relativity", title: "Light stretch" },
    { category: "Astrochemistry", title: "Gas swirl" },
    { category: "Physics", title: "Time fold" },
    { category: "Engineering", title: "Rocket thrust" },
    { category: "Mathematics", title: "Curve map" },
  ],
  Physics: [
    { category: "Thermodynamics", title: "Entropy rise" },
    { category: "Electromagnetism", title: "Wave clash" },
    { category: "Relativity", title: "Gravity pull" },
    { category: "Particle Physics", title: "Electron leap" },
    { category: "Optics", title: "Light bend" },
    { category: "Mechanics", title: "Force balance" },
    { category: "Acoustics", title: "Echo fade" },
    { category: "Fluid Dynamics", title: "Current swirl" },
    { category: "Quantum Mechanics", title: "Spin flip" },
    { category: "Astrophysics", title: "Red shift" },
  ],
  Systems: [
    { category: "Cybernetics", title: "Control loop" },
    { category: "Mathematics", title: "Pattern break" },
    { category: "Sociology", title: "Trust web" },
    { category: "Engineering", title: "Gear sync" },
    { category: "Computer Science", title: "Bit flip" },
    { category: "Ecology", title: "Food link" },
    { category: "Economics", title: "Price swing" },
    { category: "Biology", title: "Nerve net" },
    { category: "Physics", title: "Energy drop" },
    { category: "Statistics", title: "Odds curve" },
  ],
  Elements: [
    { category: "Chemistry", title: "Atom bond" },
    { category: "Geology", title: "Crystal form" },
    { category: "Biochemistry", title: "Protein twist" },
    { category: "Meteorology", title: "Cloud drift" },
    { category: "Oceanography", title: "Salt flow" },
    { category: "Materials Science", title: "Steel stretch" },
    { category: "Thermodynamics", title: "Gas expand" },
    { category: "Particle Physics", title: "Proton charge" },
    { category: "Astronomy", title: "Dust cloud" },
    { category: "Physics", title: "Heat sink" },
  ],
  Life: [
    { category: "Genetics", title: "Gene edit" },
    { category: "Microbiology", title: "Germ grow" },
    { category: "Botany", title: "Leaf turn" },
    { category: "Zoology", title: "Fish school" },
    { category: "Biophysics", title: "Pulse rhythm" },
    { category: "Evolution", title: "Adapt edge" },
    { category: "Ecology", title: "Soil life" },
    { category: "Physiology", title: "Sweat cool" },
    { category: "Anthropology", title: "Tool craft" },
    { category: "Biology", title: "Seed sprout" },
  ],
  Time: [
    { category: "History", title: "Stone age" },
    { category: "Archaeology", title: "Bone clues" },
    { category: "Cosmology", title: "Universe birth" },
    { category: "Geology", title: "Rock layer" },
    { category: "Paleontology", title: "Dino tracks" },
    { category: "Physics", title: "Clock tick" },
    { category: "Astronomy", title: "Star age" },
    { category: "Anthropology", title: "Fire use" },
    { category: "Chronobiology", title: "Sleep phase" },
    { category: "Mathematics", title: "Cycle math" },
  ],
  Thought: [
    { category: "Philosophy", title: "Mind puzzle" },
    { category: "Psychology", title: "Hope spark" },
    { category: "Logic", title: "Reason gap" },
    { category: "Ethics", title: "Duty call" },
    { category: "Linguistics", title: "Name power" },
    { category: "Sociology", title: "Faith bond" },
    { category: "Cognitive Science", title: "Idea clash" },
    { category: "Education", title: "Wisdom path" },
    { category: "Neuroscience", title: "Thought trace" },
    { category: "History", title: "Myth rise" },
  ],
  Forces: [
    { category: "Physics", title: "Magnet pull" },
    { category: "Mechanics", title: "Friction stop" },
    { category: "Electromagnetism", title: "Charge flow" },
    { category: "Thermodynamics", title: "Cold snap" },
    { category: "Fluid Dynamics", title: "Wind twist" },
    { category: "Geophysics", title: "Quake rumble" },
    { category: "Astronomy", title: "Tide lift" },
    { category: "Chemistry", title: "Reaction burst" },
    { category: "Engineering", title: "Lever lift" },
    { category: "Biophysics", title: "Tension snap" },
  ],
  Earth: [
    { category: "Geology", title: "Plate clash" },
    { category: "Volcanology", title: "Lava glow" },
    { category: "Oceanography", title: "Wave crest" },
    { category: "Meteorology", title: "Storm eye" },
    { category: "Climatology", title: "Ice cap" },
    { category: "Hydrology", title: "River bend" },
    { category: "Seismology", title: "Fault slip" },
    { category: "Mineralogy", title: "Gem cut" },
    { category: "Ecology", title: "Tree ring" },
    { category: "Geography", title: "Peak rise" },
  ],
  Tech: [
    { category: "Engineering", title: "Wheel spin" },
    { category: "Computer Science", title: "Chip speed" },
    { category: "Robotics", title: "Arm bend" },
    { category: "Materials Science", title: "Glass strength" },
    { category: "Aeronautics", title: "Wing tilt" },
    { category: "Nanotechnology", title: "Atom stack" },
    { category: "Energy", title: "Solar flare" },
    { category: "Biotechnology", title: "Cell tweak" },
    { category: "Electronics", title: "Wire hum" },
    { category: "Physics", title: "Laser beam" },
  ],
  Numbers: [
    { category: "Mathematics", title: "Prime hunt" },
    { category: "Statistics", title: "Chance roll" },
    { category: "Geometry", title: "Angle cut" },
    { category: "Algebra", title: "Root solve" },
    { category: "Calculus", title: "Slope rise" },
    { category: "Number Theory", title: "Odd twist" },
    { category: "Cryptography", title: "Key lock" },
    { category: "Probability", title: "Risk bet" },
    { category: "Topology", title: "Knot tie" },
    { category: "Logic", title: "Set clash" },
  ],
  Society: [
    { category: "Sociology", title: "Clan rule" },
    { category: "Anthropology", title: "Rite mark" },
    { category: "Economics", title: "Coin trade" },
    { category: "Politics", title: "Vote shift" },
    { category: "History", title: "Wall fall" },
    { category: "Psychology", title: "Peer push" },
    { category: "Education", title: "Class gap" },
    { category: "Linguistics", title: "Slang birth" },
    { category: "Ethics", title: "Law bend" },
    { category: "Geography", title: "Border draw" },
  ],
  Matter: [
    { category: "Chemistry", title: "Molecule dance" },
    { category: "Physics", title: "Mass pull" },
    { category: "Biochemistry", title: "Lipid fold" },
    { category: "Materials Science", title: "Rust creep" },
    { category: "Geology", title: "Sand drift" },
    { category: "Particle Physics", title: "Boson spark" },
    { category: "Thermodynamics", title: "Steam push" },
    { category: "Astronomy", title: "Nebula glow" },
    { category: "Engineering", title: "Bolt hold" },
    { category: "Biology", title: "Fiber stretch" },
  ],
  Change: [
    { category: "Evolution", title: "Wing grow" },
    { category: "Climate", title: "Rain drop" },
    { category: "History", title: "Wheel turn" },
    { category: "Physics", title: "Phase shift" },
    { category: "Sociology", title: "Trend fade" },
    { category: "Biology", title: "Hormone flux" },
    { category: "Geology", title: "Erosion cut" },
    { category: "Economics", title: "Boom crash" },
    { category: "Psychology", title: "Mood lift" },
    { category: "Technology", title: "Code update" },
  ],
};
